export interface Project {
  slug: string
  name: string
  developer: string
  location: string
  city: "Dubai" | "Abu Dhabi" | "Ras Al Khaimah"
  propertyType: string
  startingPrice: string
  priceNumeric: number
  approxSize: string
  handover: string
  paymentPlan: string
  image: string
  gallery: string[]
  isWaterfront?: boolean
}

export const projects: Project[] = [
  {
    slug: "palmiera-collective-the-oasis",
    name: "Palmiera Collective - The Oasis",
    developer: "Emaar",
    location: "The Oasis, Dubai",
    city: "Dubai",
    propertyType: "Ultra-Luxury Villas",
    startingPrice: "16,000,000",
    priceNumeric: 16000000,
    approxSize: "7,880 - 8,100",
    handover: "Q1 2029",
    paymentPlan: "10% booking, 70% during construction, 20% on handover",
    image: "/projects/palmiera.jpg",
    gallery: ["/projects/palmiera.jpg"],
  },
  {
    slug: "the-valley",
    name: "The Valley",
    developer: "Emaar",
    location: "Dubai-Al Ain Road",
    city: "Dubai",
    propertyType: "Townhouses & Villas",
    startingPrice: "2,100,000",
    priceNumeric: 2100000,
    approxSize: "1,900 - 7,800+",
    handover: "2026-2030",
    paymentPlan: "10% booking, 70% during construction, 20% on handover",
    image: "/projects/the-valley.jpg",
    gallery: ["/projects/the-valley.jpg"],
  },
  {
    slug: "emaar-south",
    name: "Emaar South",
    developer: "Emaar",
    location: "Dubai South",
    city: "Dubai",
    propertyType: "Apartments, Townhouses, Villas",
    startingPrice: "850,000",
    priceNumeric: 850000,
    approxSize: "650 - 3,700+",
    handover: "2028-2029",
    paymentPlan: "10% booking, 70% construction-linked, 20% on handover",
    image: "/projects/emaar-south.jpg",
    gallery: ["/projects/emaar-south.jpg"],
  },
  {
    slug: "emaar-beachfront",
    name: "Emaar Beachfront",
    developer: "Emaar",
    location: "Dubai Harbour",
    city: "Dubai",
    propertyType: "Apartments & Penthouses",
    startingPrice: "3,660,000",
    priceNumeric: 3660000,
    approxSize: "825 - 2,600+",
    handover: "Q3 2029",
    paymentPlan: "10% booking, 80% during construction, 10% on handover",
    image: "/projects/emaar-beachfront.jpg",
    gallery: ["/projects/emaar-beachfront.jpg"],
    isWaterfront: true,
  },
  {
    slug: "mercedes-benz-places",
    name: "Mercedes-Benz Places",
    developer: "Binghatti",
    location: "Downtown Dubai",
    city: "Dubai",
    propertyType: "Branded Apartments & Penthouses",
    startingPrice: "1,200,000",
    priceNumeric: 1200000,
    approxSize: "370 - 3,000+",
    handover: "Q2 2029",
    paymentPlan: "20% booking, 50% during construction, 30% on handover",
    image: "/projects/mercedes-benz.jpg",
    gallery: ["/projects/mercedes-benz.jpg"],
  },
  {
    slug: "binghatti-luxuria",
    name: "Binghatti Luxuria",
    developer: "Binghatti",
    location: "JVT",
    city: "Dubai",
    propertyType: "Apartments",
    startingPrice: "770,000",
    priceNumeric: 770000,
    approxSize: "420 - 1,300",
    handover: "Q3 2027",
    paymentPlan: "20% booking, 50% during construction, 30% on handover",
    image: "/projects/binghatti-luxuria.jpg",
    gallery: ["/projects/binghatti-luxuria.jpg"],
  },
  {
    slug: "binghatti-sky-terraces",
    name: "Binghatti Sky Terraces",
    developer: "Binghatti",
    location: "Motor City",
    city: "Dubai",
    propertyType: "Apartments",
    startingPrice: "804,000",
    priceNumeric: 804000,
    approxSize: "450 - 1,400",
    handover: "Q4 2027",
    paymentPlan: "20% booking, 50% during construction, 30% on handover",
    image: "/projects/binghatti-sky-terraces.jpg",
    gallery: ["/projects/binghatti-sky-terraces.jpg"],
  },
  {
    slug: "the-edit",
    name: "The Edit",
    developer: "Meraas",
    location: "Dubai Design District (D3)",
    city: "Dubai",
    propertyType: "Apartments",
    startingPrice: "4,300,000",
    priceNumeric: 4300000,
    approxSize: "1,100 - 2,500",
    handover: "Q2 2030",
    paymentPlan: "20% booking, 60% during construction, 20% on handover",
    image: "/projects/the-edit.jpg",
    gallery: ["/projects/the-edit.jpg"],
  },
  {
    slug: "crestlane",
    name: "Crestlane",
    developer: "Meraas",
    location: "City Walk",
    city: "Dubai",
    propertyType: "Apartments",
    startingPrice: "2,800,000",
    priceNumeric: 2800000,
    approxSize: "900 - 2,200",
    handover: "Q2 2030",
    paymentPlan: "20% booking, 60% construction-linked, 20% on handover",
    image: "/projects/crestlane.jpg",
    gallery: ["/projects/crestlane.jpg"],
  },
  {
    slug: "solaya",
    name: "Solaya",
    developer: "Meraas",
    location: "La Mer, Jumeirah 1",
    city: "Dubai",
    propertyType: "Ultra-Luxury Apartments",
    startingPrice: "34,000,000",
    priceNumeric: 34000000,
    approxSize: "4,000 - 9,000+",
    handover: "2029",
    paymentPlan: "20% booking, 60% during construction, 20% on handover",
    image: "/projects/solaya.jpg",
    gallery: ["/projects/solaya.jpg"],
    isWaterfront: true,
  },
  {
    slug: "nad-al-sheba-gardens",
    name: "Nad Al Sheba Gardens",
    developer: "Meraas",
    location: "Nad Al Sheba 1",
    city: "Dubai",
    propertyType: "Townhouses & Villas",
    startingPrice: "4,100,000",
    priceNumeric: 4100000,
    approxSize: "2,600 - 7,000+",
    handover: "Q2 2029",
    paymentPlan: "10% booking, 70% during construction, 20% on handover",
    image: "/projects/nad-al-sheba.jpg",
    gallery: ["/projects/nad-al-sheba.jpg"],
  },
  {
    slug: "bella-by-passo",
    name: "Bella by Passo",
    developer: "Beyond",
    location: "Palm Jumeirah - West Crescent",
    city: "Dubai",
    propertyType: "Apartments",
    startingPrice: "2,300,000",
    priceNumeric: 2300000,
    approxSize: "800 - 2,000",
    handover: "Q3 2029",
    paymentPlan: "20% booking, 60% during construction, 20% on handover",
    image: "/projects/bella-by-passo.jpg",
    gallery: ["/projects/bella-by-passo.jpg"],
    isWaterfront: true,
  },
  {
    slug: "hado",
    name: "Hado",
    developer: "Beyond",
    location: "Dubai Islands",
    city: "Dubai",
    propertyType: "Apartments",
    startingPrice: "2,300,000",
    priceNumeric: 2300000,
    approxSize: "780 - 1,900",
    handover: "2029",
    paymentPlan: "20% booking, 60% during construction, 20% on handover",
    image: "/projects/hado.jpg",
    gallery: ["/projects/hado.jpg"],
    isWaterfront: true,
  },
  {
    slug: "aqua-maya",
    name: "Aqua Maya",
    developer: "BNW Developers",
    location: "Al Marjan Island, RAK",
    city: "Ras Al Khaimah",
    propertyType: "Apartments",
    startingPrice: "2,200,000",
    priceNumeric: 2200000,
    approxSize: "750 - 1,800",
    handover: "Q4 2027",
    paymentPlan: "20% booking, 50% during construction, 30% on handover",
    image: "/projects/aqua-maya.jpg",
    gallery: ["/projects/aqua-maya.jpg"],
    isWaterfront: true,
  },
]
